- name: Adding aliases
  loop: "{{ aliases | dict2items }}"
  lineinfile:
    path: /etc/hosts
    line: "{{ item.value }} {{ item.key }}"

- name: Add password to rockyou wordlist
  lineinfile:
    path: /usr/share/wordlists/rockyou.txt
    line: Password123

- name: Remove all other wordlists except rockyou
  file:
    path: "/usr/share/wordlists/{{ item }}"
    state: absent
  loop:
    - dirb
    - dirbuster
    - fern-wifi
    - metasploit
    - nmap.lst
    - wfuzz
