- name: Adding aliases
  loop: "{{ aliases | dict2items }}"
  lineinfile:
    path: /etc/hosts
    line: "{{ item.value }} {{ item.key }}"

- name: Remove wordlists
  file:
      path: "/usr/share/wordlists/{{ item }}"
      state: absent
  with_items:
    -  dirb
    -  dirbuster
    -  fern-wifi
    -  metasploit
    -  nmap.lst
    -  wfuzz
    -  rockyou.txt.gz
